"""
recognition/base_engine.py

Abstract base class for all chemical structure recognition engines.

Every recognition engine must inherit from BaseRecognitionEngine and
implement the required methods.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional

from .result import RecognitionResult


class BaseRecognitionEngine(ABC):
    """
    Base class for all chemical OCR engines.

    Examples
    --------
    class MyEngine(BaseRecognitionEngine):
        def load(self):
            ...

        def recognize(self, image_path):
            ...

    """

    def __init__(self, name: str):
        self.name = name
        self._loaded = False

    @property
    def loaded(self) -> bool:
        """
        Returns True if the model has already been loaded.
        """
        return self._loaded

    @abstractmethod
    def load(self) -> None:
        """
        Load the recognition model into memory.

        This method should be called only once.
        """
        ...

    @abstractmethod
    def recognize(
        self,
        image_path: Path,
    ) -> RecognitionResult:
        """
        Recognize a chemical structure from an image.

        Parameters
        ----------
        image_path : Path
            Path to the cropped chemical structure image.

        Returns
        -------
        RecognitionResult
            Recognition result generated by the engine.
        """
        ...

    def ensure_loaded(self) -> None:
        """
        Lazily loads the model if it has not already been loaded.
        """
        if not self._loaded:
            self.load()
            self._loaded = True

    def unload(self) -> None:
        """
        Optional cleanup hook.

        Override this if the engine allocates GPU memory or
        other external resources.
        """
        self._loaded = False

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}"
            f"(name='{self.name}', loaded={self.loaded})"
        )